#!/bin/sh

#fechar conexões porta 22 e abrir para um host especifico
#podera adicionar para rodar no boot /etc/rc.local /usr/loca/bin/firewall
#limpar regras iptables -F
#listar regras iptables -L

iptables -A INPUT -p tcp -s 192.168.0.10 --dport 22 -j ACCEPT

iptables -A INPUT -i eth0 -p tcp --dport 22 -j REJECT
